### ISSUE TITLE
The criteria for placing students in their year

### ISSUE THREAD

**Issue by ryannitz** [ZekyTeky/Team6#54]
For year distribution, I assume we are placing them into the bin where they have completed the highest year based on their credit hours. 

Example: I am in second year, however the system will say I am in first year because that is my highest year that I have fully completed. Not the year that I am currently in.

 Is this the proper implementation? 
Are the values that are currently in the code correct? find: Cohort.addTranscript()

**Comment by uwera** [comment]
Yes. A student's year of study is determined by the number of credit hours they have completed.
The minimum credit hours required for second, third, and fourth year are specified in the rank schema. (First year is not included because we are assuming that the minimum credit hours = 0.00)

Also, replaced the values in Cohort.addTranscript with methods to get the minimum required  credit hours from the config file..
